/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as AuthenticatedToolkitRouteImport } from './routes/_authenticated.toolkit'
import { Route as AuthenticatedSoundBoardRouteImport } from './routes/_authenticated.sound-board'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated.resources'
import { Route as AuthenticatedClassesIndexRouteImport } from './routes/_authenticated.classes.index'
import { Route as AuthenticatedResourcesResourceIdRouteImport } from './routes/_authenticated.resources.$resourceId'
import { Route as AuthenticatedReportsClassIdRouteImport } from './routes/_authenticated.reports.$classId'
import { Route as AuthenticatedParentsClassIdRouteImport } from './routes/_authenticated.parents.$classId'
import { Route as AuthenticatedGamificationClassIdRouteImport } from './routes/_authenticated.gamification.$classId'
import { Route as AuthenticatedDailyClassIdRouteImport } from './routes/_authenticated.daily.$classId'
import { Route as AuthenticatedClassesClassIdRouteImport } from './routes/_authenticated.classes.$classId'
import { Route as AuthenticatedBulletinsClassIdRouteImport } from './routes/_authenticated.bulletins.$classId'
import { Route as AuthenticatedClassesClassIdDisplayRouteImport } from './routes/_authenticated.classes.$classId.display'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToolkitRoute = AuthenticatedToolkitRouteImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSoundBoardRoute = AuthenticatedSoundBoardRouteImport.update({
  id: '/sound-board',
  path: '/sound-board',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassesIndexRoute =
  AuthenticatedClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResourcesResourceIdRoute =
  AuthenticatedResourcesResourceIdRouteImport.update({
    id: '/$resourceId',
    path: '/$resourceId',
    getParentRoute: () => AuthenticatedResourcesRoute,
  } as any)
const AuthenticatedReportsClassIdRoute =
  AuthenticatedReportsClassIdRouteImport.update({
    id: '/reports/$classId',
    path: '/reports/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedParentsClassIdRoute =
  AuthenticatedParentsClassIdRouteImport.update({
    id: '/parents/$classId',
    path: '/parents/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGamificationClassIdRoute =
  AuthenticatedGamificationClassIdRouteImport.update({
    id: '/gamification/$classId',
    path: '/gamification/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDailyClassIdRoute =
  AuthenticatedDailyClassIdRouteImport.update({
    id: '/daily/$classId',
    path: '/daily/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassesClassIdRoute =
  AuthenticatedClassesClassIdRouteImport.update({
    id: '/classes/$classId',
    path: '/classes/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBulletinsClassIdRoute =
  AuthenticatedBulletinsClassIdRouteImport.update({
    id: '/bulletins/$classId',
    path: '/bulletins/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassesClassIdDisplayRoute =
  AuthenticatedClassesClassIdDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedClassesClassIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/resources': typeof AuthenticatedResourcesRouteWithChildren
  '/sound-board': typeof AuthenticatedSoundBoardRoute
  '/toolkit': typeof AuthenticatedToolkitRoute
  '/p/$token': typeof PTokenRoute
  '/bulletins/$classId': typeof AuthenticatedBulletinsClassIdRoute
  '/classes/$classId': typeof AuthenticatedClassesClassIdRouteWithChildren
  '/daily/$classId': typeof AuthenticatedDailyClassIdRoute
  '/gamification/$classId': typeof AuthenticatedGamificationClassIdRoute
  '/parents/$classId': typeof AuthenticatedParentsClassIdRoute
  '/reports/$classId': typeof AuthenticatedReportsClassIdRoute
  '/resources/$resourceId': typeof AuthenticatedResourcesResourceIdRoute
  '/classes/': typeof AuthenticatedClassesIndexRoute
  '/classes/$classId/display': typeof AuthenticatedClassesClassIdDisplayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/resources': typeof AuthenticatedResourcesRouteWithChildren
  '/sound-board': typeof AuthenticatedSoundBoardRoute
  '/toolkit': typeof AuthenticatedToolkitRoute
  '/p/$token': typeof PTokenRoute
  '/bulletins/$classId': typeof AuthenticatedBulletinsClassIdRoute
  '/classes/$classId': typeof AuthenticatedClassesClassIdRouteWithChildren
  '/daily/$classId': typeof AuthenticatedDailyClassIdRoute
  '/gamification/$classId': typeof AuthenticatedGamificationClassIdRoute
  '/parents/$classId': typeof AuthenticatedParentsClassIdRoute
  '/reports/$classId': typeof AuthenticatedReportsClassIdRoute
  '/resources/$resourceId': typeof AuthenticatedResourcesResourceIdRoute
  '/classes': typeof AuthenticatedClassesIndexRoute
  '/classes/$classId/display': typeof AuthenticatedClassesClassIdDisplayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/blog': typeof BlogRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRouteWithChildren
  '/_authenticated/sound-board': typeof AuthenticatedSoundBoardRoute
  '/_authenticated/toolkit': typeof AuthenticatedToolkitRoute
  '/p/$token': typeof PTokenRoute
  '/_authenticated/bulletins/$classId': typeof AuthenticatedBulletinsClassIdRoute
  '/_authenticated/classes/$classId': typeof AuthenticatedClassesClassIdRouteWithChildren
  '/_authenticated/daily/$classId': typeof AuthenticatedDailyClassIdRoute
  '/_authenticated/gamification/$classId': typeof AuthenticatedGamificationClassIdRoute
  '/_authenticated/parents/$classId': typeof AuthenticatedParentsClassIdRoute
  '/_authenticated/reports/$classId': typeof AuthenticatedReportsClassIdRoute
  '/_authenticated/resources/$resourceId': typeof AuthenticatedResourcesResourceIdRoute
  '/_authenticated/classes/': typeof AuthenticatedClassesIndexRoute
  '/_authenticated/classes/$classId/display': typeof AuthenticatedClassesClassIdDisplayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/login'
    | '/sitemap.xml'
    | '/resources'
    | '/sound-board'
    | '/toolkit'
    | '/p/$token'
    | '/bulletins/$classId'
    | '/classes/$classId'
    | '/daily/$classId'
    | '/gamification/$classId'
    | '/parents/$classId'
    | '/reports/$classId'
    | '/resources/$resourceId'
    | '/classes/'
    | '/classes/$classId/display'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/login'
    | '/sitemap.xml'
    | '/resources'
    | '/sound-board'
    | '/toolkit'
    | '/p/$token'
    | '/bulletins/$classId'
    | '/classes/$classId'
    | '/daily/$classId'
    | '/gamification/$classId'
    | '/parents/$classId'
    | '/reports/$classId'
    | '/resources/$resourceId'
    | '/classes'
    | '/classes/$classId/display'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/blog'
    | '/login'
    | '/sitemap.xml'
    | '/_authenticated/resources'
    | '/_authenticated/sound-board'
    | '/_authenticated/toolkit'
    | '/p/$token'
    | '/_authenticated/bulletins/$classId'
    | '/_authenticated/classes/$classId'
    | '/_authenticated/daily/$classId'
    | '/_authenticated/gamification/$classId'
    | '/_authenticated/parents/$classId'
    | '/_authenticated/reports/$classId'
    | '/_authenticated/resources/$resourceId'
    | '/_authenticated/classes/'
    | '/_authenticated/classes/$classId/display'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BlogRoute: typeof BlogRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PTokenRoute: typeof PTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/toolkit': {
      id: '/_authenticated/toolkit'
      path: '/toolkit'
      fullPath: '/toolkit'
      preLoaderRoute: typeof AuthenticatedToolkitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sound-board': {
      id: '/_authenticated/sound-board'
      path: '/sound-board'
      fullPath: '/sound-board'
      preLoaderRoute: typeof AuthenticatedSoundBoardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/': {
      id: '/_authenticated/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof AuthenticatedClassesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resources/$resourceId': {
      id: '/_authenticated/resources/$resourceId'
      path: '/$resourceId'
      fullPath: '/resources/$resourceId'
      preLoaderRoute: typeof AuthenticatedResourcesResourceIdRouteImport
      parentRoute: typeof AuthenticatedResourcesRoute
    }
    '/_authenticated/reports/$classId': {
      id: '/_authenticated/reports/$classId'
      path: '/reports/$classId'
      fullPath: '/reports/$classId'
      preLoaderRoute: typeof AuthenticatedReportsClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parents/$classId': {
      id: '/_authenticated/parents/$classId'
      path: '/parents/$classId'
      fullPath: '/parents/$classId'
      preLoaderRoute: typeof AuthenticatedParentsClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gamification/$classId': {
      id: '/_authenticated/gamification/$classId'
      path: '/gamification/$classId'
      fullPath: '/gamification/$classId'
      preLoaderRoute: typeof AuthenticatedGamificationClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daily/$classId': {
      id: '/_authenticated/daily/$classId'
      path: '/daily/$classId'
      fullPath: '/daily/$classId'
      preLoaderRoute: typeof AuthenticatedDailyClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/$classId': {
      id: '/_authenticated/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof AuthenticatedClassesClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bulletins/$classId': {
      id: '/_authenticated/bulletins/$classId'
      path: '/bulletins/$classId'
      fullPath: '/bulletins/$classId'
      preLoaderRoute: typeof AuthenticatedBulletinsClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/$classId/display': {
      id: '/_authenticated/classes/$classId/display'
      path: '/display'
      fullPath: '/classes/$classId/display'
      preLoaderRoute: typeof AuthenticatedClassesClassIdDisplayRouteImport
      parentRoute: typeof AuthenticatedClassesClassIdRoute
    }
  }
}

interface AuthenticatedResourcesRouteChildren {
  AuthenticatedResourcesResourceIdRoute: typeof AuthenticatedResourcesResourceIdRoute
}

const AuthenticatedResourcesRouteChildren: AuthenticatedResourcesRouteChildren =
  {
    AuthenticatedResourcesResourceIdRoute:
      AuthenticatedResourcesResourceIdRoute,
  }

const AuthenticatedResourcesRouteWithChildren =
  AuthenticatedResourcesRoute._addFileChildren(
    AuthenticatedResourcesRouteChildren,
  )

interface AuthenticatedClassesClassIdRouteChildren {
  AuthenticatedClassesClassIdDisplayRoute: typeof AuthenticatedClassesClassIdDisplayRoute
}

const AuthenticatedClassesClassIdRouteChildren: AuthenticatedClassesClassIdRouteChildren =
  {
    AuthenticatedClassesClassIdDisplayRoute:
      AuthenticatedClassesClassIdDisplayRoute,
  }

const AuthenticatedClassesClassIdRouteWithChildren =
  AuthenticatedClassesClassIdRoute._addFileChildren(
    AuthenticatedClassesClassIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRouteWithChildren
  AuthenticatedSoundBoardRoute: typeof AuthenticatedSoundBoardRoute
  AuthenticatedToolkitRoute: typeof AuthenticatedToolkitRoute
  AuthenticatedBulletinsClassIdRoute: typeof AuthenticatedBulletinsClassIdRoute
  AuthenticatedClassesClassIdRoute: typeof AuthenticatedClassesClassIdRouteWithChildren
  AuthenticatedDailyClassIdRoute: typeof AuthenticatedDailyClassIdRoute
  AuthenticatedGamificationClassIdRoute: typeof AuthenticatedGamificationClassIdRoute
  AuthenticatedParentsClassIdRoute: typeof AuthenticatedParentsClassIdRoute
  AuthenticatedReportsClassIdRoute: typeof AuthenticatedReportsClassIdRoute
  AuthenticatedClassesIndexRoute: typeof AuthenticatedClassesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedResourcesRoute: AuthenticatedResourcesRouteWithChildren,
  AuthenticatedSoundBoardRoute: AuthenticatedSoundBoardRoute,
  AuthenticatedToolkitRoute: AuthenticatedToolkitRoute,
  AuthenticatedBulletinsClassIdRoute: AuthenticatedBulletinsClassIdRoute,
  AuthenticatedClassesClassIdRoute:
    AuthenticatedClassesClassIdRouteWithChildren,
  AuthenticatedDailyClassIdRoute: AuthenticatedDailyClassIdRoute,
  AuthenticatedGamificationClassIdRoute: AuthenticatedGamificationClassIdRoute,
  AuthenticatedParentsClassIdRoute: AuthenticatedParentsClassIdRoute,
  AuthenticatedReportsClassIdRoute: AuthenticatedReportsClassIdRoute,
  AuthenticatedClassesIndexRoute: AuthenticatedClassesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BlogRoute: BlogRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PTokenRoute: PTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
