/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedClassesIndexRouteImport } from './routes/_authenticated.classes.index'
import { Route as AuthenticatedReportsClassIdRouteImport } from './routes/_authenticated.reports.$classId'
import { Route as AuthenticatedClassesClassIdRouteImport } from './routes/_authenticated.classes.$classId'
import { Route as AuthenticatedBulletinsClassIdRouteImport } from './routes/_authenticated.bulletins.$classId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClassesIndexRoute =
  AuthenticatedClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsClassIdRoute =
  AuthenticatedReportsClassIdRouteImport.update({
    id: '/reports/$classId',
    path: '/reports/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassesClassIdRoute =
  AuthenticatedClassesClassIdRouteImport.update({
    id: '/classes/$classId',
    path: '/classes/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBulletinsClassIdRoute =
  AuthenticatedBulletinsClassIdRouteImport.update({
    id: '/bulletins/$classId',
    path: '/bulletins/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bulletins/$classId': typeof AuthenticatedBulletinsClassIdRoute
  '/classes/$classId': typeof AuthenticatedClassesClassIdRoute
  '/reports/$classId': typeof AuthenticatedReportsClassIdRoute
  '/classes/': typeof AuthenticatedClassesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bulletins/$classId': typeof AuthenticatedBulletinsClassIdRoute
  '/classes/$classId': typeof AuthenticatedClassesClassIdRoute
  '/reports/$classId': typeof AuthenticatedReportsClassIdRoute
  '/classes': typeof AuthenticatedClassesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/bulletins/$classId': typeof AuthenticatedBulletinsClassIdRoute
  '/_authenticated/classes/$classId': typeof AuthenticatedClassesClassIdRoute
  '/_authenticated/reports/$classId': typeof AuthenticatedReportsClassIdRoute
  '/_authenticated/classes/': typeof AuthenticatedClassesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bulletins/$classId'
    | '/classes/$classId'
    | '/reports/$classId'
    | '/classes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/bulletins/$classId'
    | '/classes/$classId'
    | '/reports/$classId'
    | '/classes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/bulletins/$classId'
    | '/_authenticated/classes/$classId'
    | '/_authenticated/reports/$classId'
    | '/_authenticated/classes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/classes/': {
      id: '/_authenticated/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof AuthenticatedClassesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/$classId': {
      id: '/_authenticated/reports/$classId'
      path: '/reports/$classId'
      fullPath: '/reports/$classId'
      preLoaderRoute: typeof AuthenticatedReportsClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/$classId': {
      id: '/_authenticated/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof AuthenticatedClassesClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bulletins/$classId': {
      id: '/_authenticated/bulletins/$classId'
      path: '/bulletins/$classId'
      fullPath: '/bulletins/$classId'
      preLoaderRoute: typeof AuthenticatedBulletinsClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBulletinsClassIdRoute: typeof AuthenticatedBulletinsClassIdRoute
  AuthenticatedClassesClassIdRoute: typeof AuthenticatedClassesClassIdRoute
  AuthenticatedReportsClassIdRoute: typeof AuthenticatedReportsClassIdRoute
  AuthenticatedClassesIndexRoute: typeof AuthenticatedClassesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBulletinsClassIdRoute: AuthenticatedBulletinsClassIdRoute,
  AuthenticatedClassesClassIdRoute: AuthenticatedClassesClassIdRoute,
  AuthenticatedReportsClassIdRoute: AuthenticatedReportsClassIdRoute,
  AuthenticatedClassesIndexRoute: AuthenticatedClassesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
