/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ParentsGuideRouteImport } from './routes/parents-guide'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParentsGuideIndexRouteImport } from './routes/parents-guide.index'
import { Route as HelpIndexRouteImport } from './routes/help.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ToolsGroupMakerRouteImport } from './routes/tools.group-maker'
import { Route as PartnersSchoolsRouteImport } from './routes/partners.schools'
import { Route as PartnersDistrictsRouteImport } from './routes/partners.districts'
import { Route as PartnersCaseStudiesRouteImport } from './routes/partners.case-studies'
import { Route as ParentsGuideSlugRouteImport } from './routes/parents-guide.$slug'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as HelpSlugRouteImport } from './routes/help.$slug'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as BlogWeeklyReportTemplateRouteImport } from './routes/blog.weekly-report-template'
import { Route as BlogProgressTrackingGuideRouteImport } from './routes/blog.progress-tracking-guide'
import { Route as BlogDigitalHallPassGuideRouteImport } from './routes/blog.digital-hall-pass-guide'
import { Route as BlogClassroomToolsTeachersRouteImport } from './routes/blog.classroom-tools-teachers'
import { Route as AuthenticatedToolkitRouteImport } from './routes/_authenticated.toolkit'
import { Route as AuthenticatedSoundBoardRouteImport } from './routes/_authenticated.sound-board'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated.resources'
import { Route as AuthenticatedQuestionsRouteImport } from './routes/_authenticated.questions'
import { Route as AuthenticatedIngestRouteImport } from './routes/_authenticated.ingest'
import { Route as AuthenticatedClassesIndexRouteImport } from './routes/_authenticated.classes.index'
import { Route as AuthenticatedShareClassIdRouteImport } from './routes/_authenticated.share.$classId'
import { Route as AuthenticatedResourcesResourceIdRouteImport } from './routes/_authenticated.resources.$resourceId'
import { Route as AuthenticatedReportsClassIdRouteImport } from './routes/_authenticated.reports.$classId'
import { Route as AuthenticatedRaffleClassIdRouteImport } from './routes/_authenticated.raffle.$classId'
import { Route as AuthenticatedParentsClassIdRouteImport } from './routes/_authenticated.parents.$classId'
import { Route as AuthenticatedGamificationClassIdRouteImport } from './routes/_authenticated.gamification.$classId'
import { Route as AuthenticatedDailyClassIdRouteImport } from './routes/_authenticated.daily.$classId'
import { Route as AuthenticatedClassesClassIdRouteImport } from './routes/_authenticated.classes.$classId'
import { Route as AuthenticatedBulletinsClassIdRouteImport } from './routes/_authenticated.bulletins.$classId'
import { Route as AuthenticatedClassesClassIdDisplayRouteImport } from './routes/_authenticated.classes.$classId.display'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsGuideRoute = ParentsGuideRouteImport.update({
  id: '/parents-guide',
  path: '/parents-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsGuideIndexRoute = ParentsGuideIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentsGuideRoute,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HelpRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ToolsGroupMakerRoute = ToolsGroupMakerRouteImport.update({
  id: '/tools/group-maker',
  path: '/tools/group-maker',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersSchoolsRoute = PartnersSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => PartnersRoute,
} as any)
const PartnersDistrictsRoute = PartnersDistrictsRouteImport.update({
  id: '/districts',
  path: '/districts',
  getParentRoute: () => PartnersRoute,
} as any)
const PartnersCaseStudiesRoute = PartnersCaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => PartnersRoute,
} as any)
const ParentsGuideSlugRoute = ParentsGuideSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ParentsGuideRoute,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpSlugRoute = HelpSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HelpRoute,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWeeklyReportTemplateRoute =
  BlogWeeklyReportTemplateRouteImport.update({
    id: '/weekly-report-template',
    path: '/weekly-report-template',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogProgressTrackingGuideRoute =
  BlogProgressTrackingGuideRouteImport.update({
    id: '/progress-tracking-guide',
    path: '/progress-tracking-guide',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogDigitalHallPassGuideRoute =
  BlogDigitalHallPassGuideRouteImport.update({
    id: '/digital-hall-pass-guide',
    path: '/digital-hall-pass-guide',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogClassroomToolsTeachersRoute =
  BlogClassroomToolsTeachersRouteImport.update({
    id: '/classroom-tools-teachers',
    path: '/classroom-tools-teachers',
    getParentRoute: () => BlogRoute,
  } as any)
const AuthenticatedToolkitRoute = AuthenticatedToolkitRouteImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSoundBoardRoute = AuthenticatedSoundBoardRouteImport.update({
  id: '/sound-board',
  path: '/sound-board',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuestionsRoute = AuthenticatedQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIngestRoute = AuthenticatedIngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassesIndexRoute =
  AuthenticatedClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShareClassIdRoute =
  AuthenticatedShareClassIdRouteImport.update({
    id: '/share/$classId',
    path: '/share/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResourcesResourceIdRoute =
  AuthenticatedResourcesResourceIdRouteImport.update({
    id: '/$resourceId',
    path: '/$resourceId',
    getParentRoute: () => AuthenticatedResourcesRoute,
  } as any)
const AuthenticatedReportsClassIdRoute =
  AuthenticatedReportsClassIdRouteImport.update({
    id: '/reports/$classId',
    path: '/reports/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRaffleClassIdRoute =
  AuthenticatedRaffleClassIdRouteImport.update({
    id: '/raffle/$classId',
    path: '/raffle/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedParentsClassIdRoute =
  AuthenticatedParentsClassIdRouteImport.update({
    id: '/parents/$classId',
    path: '/parents/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGamificationClassIdRoute =
  AuthenticatedGamificationClassIdRouteImport.update({
    id: '/gamification/$classId',
    path: '/gamification/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDailyClassIdRoute =
  AuthenticatedDailyClassIdRouteImport.update({
    id: '/daily/$classId',
    path: '/daily/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassesClassIdRoute =
  AuthenticatedClassesClassIdRouteImport.update({
    id: '/classes/$classId',
    path: '/classes/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBulletinsClassIdRoute =
  AuthenticatedBulletinsClassIdRouteImport.update({
    id: '/bulletins/$classId',
    path: '/bulletins/$classId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassesClassIdDisplayRoute =
  AuthenticatedClassesClassIdDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedClassesClassIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/help': typeof HelpRouteWithChildren
  '/login': typeof LoginRoute
  '/parents-guide': typeof ParentsGuideRouteWithChildren
  '/partners': typeof PartnersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/ingest': typeof AuthenticatedIngestRoute
  '/questions': typeof AuthenticatedQuestionsRoute
  '/resources': typeof AuthenticatedResourcesRouteWithChildren
  '/sound-board': typeof AuthenticatedSoundBoardRoute
  '/toolkit': typeof AuthenticatedToolkitRoute
  '/blog/classroom-tools-teachers': typeof BlogClassroomToolsTeachersRoute
  '/blog/digital-hall-pass-guide': typeof BlogDigitalHallPassGuideRoute
  '/blog/progress-tracking-guide': typeof BlogProgressTrackingGuideRoute
  '/blog/weekly-report-template': typeof BlogWeeklyReportTemplateRoute
  '/c/$slug': typeof CSlugRoute
  '/help/$slug': typeof HelpSlugRoute
  '/p/$token': typeof PTokenRoute
  '/parents-guide/$slug': typeof ParentsGuideSlugRoute
  '/partners/case-studies': typeof PartnersCaseStudiesRoute
  '/partners/districts': typeof PartnersDistrictsRoute
  '/partners/schools': typeof PartnersSchoolsRoute
  '/tools/group-maker': typeof ToolsGroupMakerRoute
  '/blog/': typeof BlogIndexRoute
  '/help/': typeof HelpIndexRoute
  '/parents-guide/': typeof ParentsGuideIndexRoute
  '/bulletins/$classId': typeof AuthenticatedBulletinsClassIdRoute
  '/classes/$classId': typeof AuthenticatedClassesClassIdRouteWithChildren
  '/daily/$classId': typeof AuthenticatedDailyClassIdRoute
  '/gamification/$classId': typeof AuthenticatedGamificationClassIdRoute
  '/parents/$classId': typeof AuthenticatedParentsClassIdRoute
  '/raffle/$classId': typeof AuthenticatedRaffleClassIdRoute
  '/reports/$classId': typeof AuthenticatedReportsClassIdRoute
  '/resources/$resourceId': typeof AuthenticatedResourcesResourceIdRoute
  '/share/$classId': typeof AuthenticatedShareClassIdRoute
  '/classes/': typeof AuthenticatedClassesIndexRoute
  '/classes/$classId/display': typeof AuthenticatedClassesClassIdDisplayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/ingest': typeof AuthenticatedIngestRoute
  '/questions': typeof AuthenticatedQuestionsRoute
  '/resources': typeof AuthenticatedResourcesRouteWithChildren
  '/sound-board': typeof AuthenticatedSoundBoardRoute
  '/toolkit': typeof AuthenticatedToolkitRoute
  '/blog/classroom-tools-teachers': typeof BlogClassroomToolsTeachersRoute
  '/blog/digital-hall-pass-guide': typeof BlogDigitalHallPassGuideRoute
  '/blog/progress-tracking-guide': typeof BlogProgressTrackingGuideRoute
  '/blog/weekly-report-template': typeof BlogWeeklyReportTemplateRoute
  '/c/$slug': typeof CSlugRoute
  '/help/$slug': typeof HelpSlugRoute
  '/p/$token': typeof PTokenRoute
  '/parents-guide/$slug': typeof ParentsGuideSlugRoute
  '/partners/case-studies': typeof PartnersCaseStudiesRoute
  '/partners/districts': typeof PartnersDistrictsRoute
  '/partners/schools': typeof PartnersSchoolsRoute
  '/tools/group-maker': typeof ToolsGroupMakerRoute
  '/blog': typeof BlogIndexRoute
  '/help': typeof HelpIndexRoute
  '/parents-guide': typeof ParentsGuideIndexRoute
  '/bulletins/$classId': typeof AuthenticatedBulletinsClassIdRoute
  '/classes/$classId': typeof AuthenticatedClassesClassIdRouteWithChildren
  '/daily/$classId': typeof AuthenticatedDailyClassIdRoute
  '/gamification/$classId': typeof AuthenticatedGamificationClassIdRoute
  '/parents/$classId': typeof AuthenticatedParentsClassIdRoute
  '/raffle/$classId': typeof AuthenticatedRaffleClassIdRoute
  '/reports/$classId': typeof AuthenticatedReportsClassIdRoute
  '/resources/$resourceId': typeof AuthenticatedResourcesResourceIdRoute
  '/share/$classId': typeof AuthenticatedShareClassIdRoute
  '/classes': typeof AuthenticatedClassesIndexRoute
  '/classes/$classId/display': typeof AuthenticatedClassesClassIdDisplayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/help': typeof HelpRouteWithChildren
  '/login': typeof LoginRoute
  '/parents-guide': typeof ParentsGuideRouteWithChildren
  '/partners': typeof PartnersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/_authenticated/ingest': typeof AuthenticatedIngestRoute
  '/_authenticated/questions': typeof AuthenticatedQuestionsRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRouteWithChildren
  '/_authenticated/sound-board': typeof AuthenticatedSoundBoardRoute
  '/_authenticated/toolkit': typeof AuthenticatedToolkitRoute
  '/blog/classroom-tools-teachers': typeof BlogClassroomToolsTeachersRoute
  '/blog/digital-hall-pass-guide': typeof BlogDigitalHallPassGuideRoute
  '/blog/progress-tracking-guide': typeof BlogProgressTrackingGuideRoute
  '/blog/weekly-report-template': typeof BlogWeeklyReportTemplateRoute
  '/c/$slug': typeof CSlugRoute
  '/help/$slug': typeof HelpSlugRoute
  '/p/$token': typeof PTokenRoute
  '/parents-guide/$slug': typeof ParentsGuideSlugRoute
  '/partners/case-studies': typeof PartnersCaseStudiesRoute
  '/partners/districts': typeof PartnersDistrictsRoute
  '/partners/schools': typeof PartnersSchoolsRoute
  '/tools/group-maker': typeof ToolsGroupMakerRoute
  '/blog/': typeof BlogIndexRoute
  '/help/': typeof HelpIndexRoute
  '/parents-guide/': typeof ParentsGuideIndexRoute
  '/_authenticated/bulletins/$classId': typeof AuthenticatedBulletinsClassIdRoute
  '/_authenticated/classes/$classId': typeof AuthenticatedClassesClassIdRouteWithChildren
  '/_authenticated/daily/$classId': typeof AuthenticatedDailyClassIdRoute
  '/_authenticated/gamification/$classId': typeof AuthenticatedGamificationClassIdRoute
  '/_authenticated/parents/$classId': typeof AuthenticatedParentsClassIdRoute
  '/_authenticated/raffle/$classId': typeof AuthenticatedRaffleClassIdRoute
  '/_authenticated/reports/$classId': typeof AuthenticatedReportsClassIdRoute
  '/_authenticated/resources/$resourceId': typeof AuthenticatedResourcesResourceIdRoute
  '/_authenticated/share/$classId': typeof AuthenticatedShareClassIdRoute
  '/_authenticated/classes/': typeof AuthenticatedClassesIndexRoute
  '/_authenticated/classes/$classId/display': typeof AuthenticatedClassesClassIdDisplayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/help'
    | '/login'
    | '/parents-guide'
    | '/partners'
    | '/privacy'
    | '/sitemap.xml'
    | '/support'
    | '/ingest'
    | '/questions'
    | '/resources'
    | '/sound-board'
    | '/toolkit'
    | '/blog/classroom-tools-teachers'
    | '/blog/digital-hall-pass-guide'
    | '/blog/progress-tracking-guide'
    | '/blog/weekly-report-template'
    | '/c/$slug'
    | '/help/$slug'
    | '/p/$token'
    | '/parents-guide/$slug'
    | '/partners/case-studies'
    | '/partners/districts'
    | '/partners/schools'
    | '/tools/group-maker'
    | '/blog/'
    | '/help/'
    | '/parents-guide/'
    | '/bulletins/$classId'
    | '/classes/$classId'
    | '/daily/$classId'
    | '/gamification/$classId'
    | '/parents/$classId'
    | '/raffle/$classId'
    | '/reports/$classId'
    | '/resources/$resourceId'
    | '/share/$classId'
    | '/classes/'
    | '/classes/$classId/display'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/partners'
    | '/privacy'
    | '/sitemap.xml'
    | '/support'
    | '/ingest'
    | '/questions'
    | '/resources'
    | '/sound-board'
    | '/toolkit'
    | '/blog/classroom-tools-teachers'
    | '/blog/digital-hall-pass-guide'
    | '/blog/progress-tracking-guide'
    | '/blog/weekly-report-template'
    | '/c/$slug'
    | '/help/$slug'
    | '/p/$token'
    | '/parents-guide/$slug'
    | '/partners/case-studies'
    | '/partners/districts'
    | '/partners/schools'
    | '/tools/group-maker'
    | '/blog'
    | '/help'
    | '/parents-guide'
    | '/bulletins/$classId'
    | '/classes/$classId'
    | '/daily/$classId'
    | '/gamification/$classId'
    | '/parents/$classId'
    | '/raffle/$classId'
    | '/reports/$classId'
    | '/resources/$resourceId'
    | '/share/$classId'
    | '/classes'
    | '/classes/$classId/display'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/blog'
    | '/help'
    | '/login'
    | '/parents-guide'
    | '/partners'
    | '/privacy'
    | '/sitemap.xml'
    | '/support'
    | '/_authenticated/ingest'
    | '/_authenticated/questions'
    | '/_authenticated/resources'
    | '/_authenticated/sound-board'
    | '/_authenticated/toolkit'
    | '/blog/classroom-tools-teachers'
    | '/blog/digital-hall-pass-guide'
    | '/blog/progress-tracking-guide'
    | '/blog/weekly-report-template'
    | '/c/$slug'
    | '/help/$slug'
    | '/p/$token'
    | '/parents-guide/$slug'
    | '/partners/case-studies'
    | '/partners/districts'
    | '/partners/schools'
    | '/tools/group-maker'
    | '/blog/'
    | '/help/'
    | '/parents-guide/'
    | '/_authenticated/bulletins/$classId'
    | '/_authenticated/classes/$classId'
    | '/_authenticated/daily/$classId'
    | '/_authenticated/gamification/$classId'
    | '/_authenticated/parents/$classId'
    | '/_authenticated/raffle/$classId'
    | '/_authenticated/reports/$classId'
    | '/_authenticated/resources/$resourceId'
    | '/_authenticated/share/$classId'
    | '/_authenticated/classes/'
    | '/_authenticated/classes/$classId/display'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  HelpRoute: typeof HelpRouteWithChildren
  LoginRoute: typeof LoginRoute
  ParentsGuideRoute: typeof ParentsGuideRouteWithChildren
  PartnersRoute: typeof PartnersRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  CSlugRoute: typeof CSlugRoute
  PTokenRoute: typeof PTokenRoute
  ToolsGroupMakerRoute: typeof ToolsGroupMakerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents-guide': {
      id: '/parents-guide'
      path: '/parents-guide'
      fullPath: '/parents-guide'
      preLoaderRoute: typeof ParentsGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents-guide/': {
      id: '/parents-guide/'
      path: '/'
      fullPath: '/parents-guide/'
      preLoaderRoute: typeof ParentsGuideIndexRouteImport
      parentRoute: typeof ParentsGuideRoute
    }
    '/help/': {
      id: '/help/'
      path: '/'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof HelpRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/tools/group-maker': {
      id: '/tools/group-maker'
      path: '/tools/group-maker'
      fullPath: '/tools/group-maker'
      preLoaderRoute: typeof ToolsGroupMakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/schools': {
      id: '/partners/schools'
      path: '/schools'
      fullPath: '/partners/schools'
      preLoaderRoute: typeof PartnersSchoolsRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/partners/districts': {
      id: '/partners/districts'
      path: '/districts'
      fullPath: '/partners/districts'
      preLoaderRoute: typeof PartnersDistrictsRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/partners/case-studies': {
      id: '/partners/case-studies'
      path: '/case-studies'
      fullPath: '/partners/case-studies'
      preLoaderRoute: typeof PartnersCaseStudiesRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/parents-guide/$slug': {
      id: '/parents-guide/$slug'
      path: '/$slug'
      fullPath: '/parents-guide/$slug'
      preLoaderRoute: typeof ParentsGuideSlugRouteImport
      parentRoute: typeof ParentsGuideRoute
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/$slug': {
      id: '/help/$slug'
      path: '/$slug'
      fullPath: '/help/$slug'
      preLoaderRoute: typeof HelpSlugRouteImport
      parentRoute: typeof HelpRoute
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/weekly-report-template': {
      id: '/blog/weekly-report-template'
      path: '/weekly-report-template'
      fullPath: '/blog/weekly-report-template'
      preLoaderRoute: typeof BlogWeeklyReportTemplateRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/progress-tracking-guide': {
      id: '/blog/progress-tracking-guide'
      path: '/progress-tracking-guide'
      fullPath: '/blog/progress-tracking-guide'
      preLoaderRoute: typeof BlogProgressTrackingGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/digital-hall-pass-guide': {
      id: '/blog/digital-hall-pass-guide'
      path: '/digital-hall-pass-guide'
      fullPath: '/blog/digital-hall-pass-guide'
      preLoaderRoute: typeof BlogDigitalHallPassGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/classroom-tools-teachers': {
      id: '/blog/classroom-tools-teachers'
      path: '/classroom-tools-teachers'
      fullPath: '/blog/classroom-tools-teachers'
      preLoaderRoute: typeof BlogClassroomToolsTeachersRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/toolkit': {
      id: '/_authenticated/toolkit'
      path: '/toolkit'
      fullPath: '/toolkit'
      preLoaderRoute: typeof AuthenticatedToolkitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sound-board': {
      id: '/_authenticated/sound-board'
      path: '/sound-board'
      fullPath: '/sound-board'
      preLoaderRoute: typeof AuthenticatedSoundBoardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/questions': {
      id: '/_authenticated/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof AuthenticatedQuestionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ingest': {
      id: '/_authenticated/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof AuthenticatedIngestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/': {
      id: '/_authenticated/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof AuthenticatedClassesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/share/$classId': {
      id: '/_authenticated/share/$classId'
      path: '/share/$classId'
      fullPath: '/share/$classId'
      preLoaderRoute: typeof AuthenticatedShareClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resources/$resourceId': {
      id: '/_authenticated/resources/$resourceId'
      path: '/$resourceId'
      fullPath: '/resources/$resourceId'
      preLoaderRoute: typeof AuthenticatedResourcesResourceIdRouteImport
      parentRoute: typeof AuthenticatedResourcesRoute
    }
    '/_authenticated/reports/$classId': {
      id: '/_authenticated/reports/$classId'
      path: '/reports/$classId'
      fullPath: '/reports/$classId'
      preLoaderRoute: typeof AuthenticatedReportsClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/raffle/$classId': {
      id: '/_authenticated/raffle/$classId'
      path: '/raffle/$classId'
      fullPath: '/raffle/$classId'
      preLoaderRoute: typeof AuthenticatedRaffleClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parents/$classId': {
      id: '/_authenticated/parents/$classId'
      path: '/parents/$classId'
      fullPath: '/parents/$classId'
      preLoaderRoute: typeof AuthenticatedParentsClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gamification/$classId': {
      id: '/_authenticated/gamification/$classId'
      path: '/gamification/$classId'
      fullPath: '/gamification/$classId'
      preLoaderRoute: typeof AuthenticatedGamificationClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daily/$classId': {
      id: '/_authenticated/daily/$classId'
      path: '/daily/$classId'
      fullPath: '/daily/$classId'
      preLoaderRoute: typeof AuthenticatedDailyClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/$classId': {
      id: '/_authenticated/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof AuthenticatedClassesClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bulletins/$classId': {
      id: '/_authenticated/bulletins/$classId'
      path: '/bulletins/$classId'
      fullPath: '/bulletins/$classId'
      preLoaderRoute: typeof AuthenticatedBulletinsClassIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/$classId/display': {
      id: '/_authenticated/classes/$classId/display'
      path: '/display'
      fullPath: '/classes/$classId/display'
      preLoaderRoute: typeof AuthenticatedClassesClassIdDisplayRouteImport
      parentRoute: typeof AuthenticatedClassesClassIdRoute
    }
  }
}

interface AuthenticatedResourcesRouteChildren {
  AuthenticatedResourcesResourceIdRoute: typeof AuthenticatedResourcesResourceIdRoute
}

const AuthenticatedResourcesRouteChildren: AuthenticatedResourcesRouteChildren =
  {
    AuthenticatedResourcesResourceIdRoute:
      AuthenticatedResourcesResourceIdRoute,
  }

const AuthenticatedResourcesRouteWithChildren =
  AuthenticatedResourcesRoute._addFileChildren(
    AuthenticatedResourcesRouteChildren,
  )

interface AuthenticatedClassesClassIdRouteChildren {
  AuthenticatedClassesClassIdDisplayRoute: typeof AuthenticatedClassesClassIdDisplayRoute
}

const AuthenticatedClassesClassIdRouteChildren: AuthenticatedClassesClassIdRouteChildren =
  {
    AuthenticatedClassesClassIdDisplayRoute:
      AuthenticatedClassesClassIdDisplayRoute,
  }

const AuthenticatedClassesClassIdRouteWithChildren =
  AuthenticatedClassesClassIdRoute._addFileChildren(
    AuthenticatedClassesClassIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIngestRoute: typeof AuthenticatedIngestRoute
  AuthenticatedQuestionsRoute: typeof AuthenticatedQuestionsRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRouteWithChildren
  AuthenticatedSoundBoardRoute: typeof AuthenticatedSoundBoardRoute
  AuthenticatedToolkitRoute: typeof AuthenticatedToolkitRoute
  AuthenticatedBulletinsClassIdRoute: typeof AuthenticatedBulletinsClassIdRoute
  AuthenticatedClassesClassIdRoute: typeof AuthenticatedClassesClassIdRouteWithChildren
  AuthenticatedDailyClassIdRoute: typeof AuthenticatedDailyClassIdRoute
  AuthenticatedGamificationClassIdRoute: typeof AuthenticatedGamificationClassIdRoute
  AuthenticatedParentsClassIdRoute: typeof AuthenticatedParentsClassIdRoute
  AuthenticatedRaffleClassIdRoute: typeof AuthenticatedRaffleClassIdRoute
  AuthenticatedReportsClassIdRoute: typeof AuthenticatedReportsClassIdRoute
  AuthenticatedShareClassIdRoute: typeof AuthenticatedShareClassIdRoute
  AuthenticatedClassesIndexRoute: typeof AuthenticatedClassesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIngestRoute: AuthenticatedIngestRoute,
  AuthenticatedQuestionsRoute: AuthenticatedQuestionsRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRouteWithChildren,
  AuthenticatedSoundBoardRoute: AuthenticatedSoundBoardRoute,
  AuthenticatedToolkitRoute: AuthenticatedToolkitRoute,
  AuthenticatedBulletinsClassIdRoute: AuthenticatedBulletinsClassIdRoute,
  AuthenticatedClassesClassIdRoute:
    AuthenticatedClassesClassIdRouteWithChildren,
  AuthenticatedDailyClassIdRoute: AuthenticatedDailyClassIdRoute,
  AuthenticatedGamificationClassIdRoute: AuthenticatedGamificationClassIdRoute,
  AuthenticatedParentsClassIdRoute: AuthenticatedParentsClassIdRoute,
  AuthenticatedRaffleClassIdRoute: AuthenticatedRaffleClassIdRoute,
  AuthenticatedReportsClassIdRoute: AuthenticatedReportsClassIdRoute,
  AuthenticatedShareClassIdRoute: AuthenticatedShareClassIdRoute,
  AuthenticatedClassesIndexRoute: AuthenticatedClassesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BlogRouteChildren {
  BlogClassroomToolsTeachersRoute: typeof BlogClassroomToolsTeachersRoute
  BlogDigitalHallPassGuideRoute: typeof BlogDigitalHallPassGuideRoute
  BlogProgressTrackingGuideRoute: typeof BlogProgressTrackingGuideRoute
  BlogWeeklyReportTemplateRoute: typeof BlogWeeklyReportTemplateRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogClassroomToolsTeachersRoute: BlogClassroomToolsTeachersRoute,
  BlogDigitalHallPassGuideRoute: BlogDigitalHallPassGuideRoute,
  BlogProgressTrackingGuideRoute: BlogProgressTrackingGuideRoute,
  BlogWeeklyReportTemplateRoute: BlogWeeklyReportTemplateRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface HelpRouteChildren {
  HelpSlugRoute: typeof HelpSlugRoute
  HelpIndexRoute: typeof HelpIndexRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpSlugRoute: HelpSlugRoute,
  HelpIndexRoute: HelpIndexRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

interface ParentsGuideRouteChildren {
  ParentsGuideSlugRoute: typeof ParentsGuideSlugRoute
  ParentsGuideIndexRoute: typeof ParentsGuideIndexRoute
}

const ParentsGuideRouteChildren: ParentsGuideRouteChildren = {
  ParentsGuideSlugRoute: ParentsGuideSlugRoute,
  ParentsGuideIndexRoute: ParentsGuideIndexRoute,
}

const ParentsGuideRouteWithChildren = ParentsGuideRoute._addFileChildren(
  ParentsGuideRouteChildren,
)

interface PartnersRouteChildren {
  PartnersCaseStudiesRoute: typeof PartnersCaseStudiesRoute
  PartnersDistrictsRoute: typeof PartnersDistrictsRoute
  PartnersSchoolsRoute: typeof PartnersSchoolsRoute
}

const PartnersRouteChildren: PartnersRouteChildren = {
  PartnersCaseStudiesRoute: PartnersCaseStudiesRoute,
  PartnersDistrictsRoute: PartnersDistrictsRoute,
  PartnersSchoolsRoute: PartnersSchoolsRoute,
}

const PartnersRouteWithChildren = PartnersRoute._addFileChildren(
  PartnersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  HelpRoute: HelpRouteWithChildren,
  LoginRoute: LoginRoute,
  ParentsGuideRoute: ParentsGuideRouteWithChildren,
  PartnersRoute: PartnersRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  CSlugRoute: CSlugRoute,
  PTokenRoute: PTokenRoute,
  ToolsGroupMakerRoute: ToolsGroupMakerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
